{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Tutorial: Batch Processing\n",
    "\n",
    "This tutorial explains how to use the batch processing script to solve CommonRoad planning problems in parallel. The configuration for batch processing is stored in `batch_processing_config.yaml`. Some of the parameters are explained as follows:\n",
    "* **input_path**: input directory of your intended CommonRoad scenarios.\n",
    "* **output_path**: output directory of CommonRoad solution files.\n",
    "* **overwrite**: whether the existing solution files should be overwritten.\n",
    "* **validate_solution**: check the validity of the solutions with the feasibility checker.\n",
    "* **num_worker_processes**: the number of parallel executions of motion planners.\n",
    "\n",
    "Parameters specified under the `default` block will be applied to all scenarios. If you wish to specify a different paramter for specific scenarios, simply insert a new block with the content of the `default` block copied, and overwrite parameters therein. This new block should be named after the ID of the sceanrio that you wish to aplly the parameters to. Related parameters are explained as follows:\n",
    "* **vehicle_model**: model of the vehicle, valid values: **PM, KS, ST and MB**. Refer to [Vehicle Models](https://gitlab.lrz.de/tum-cps/commonroad-vehicle-models/-/blob/master/vehicleModels_commonRoad.pdf) for more information.\n",
    "* **vehicle_type**: type of the vehicle, valid values: **FORD_ESCORT, BMW_320i and VW_VANAGON**.\n",
    "* **cost_function**: id of cost function. Refer to [Cost Functions](https://gitlab.lrz.de/tum-cps/commonroad-cost-functions/-/blob/master/costFunctions_commonRoad.pdf) for more information.\n",
    "* **planner**: the planner that is used to solve for solutions, possible values are: bfs, dfs, dls, ucs, gbfs, astar, student, student_example\n",
    "* **planning_problem_idx**: index of the planning problem. for cooperative scenarios: 0, 1, 2, ..., otherwise: 0\n",
    "* **max_tree_depth**: maximum depth of the search tree\n",
    "* **timeout**: timeout time for motion planner [s].\n",
    "\n",
    "Note: the paths can either be **relative** or **absolute**.\n",
    "To start the search with batch processing, you can either directly run `SMP/batch_processing/batch_processing_parallel.py` in IDEs (e.g. PyCharm) with `commonroad-search/` marked as sources root, or run the following script."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Parallel Batch Processing\n",
    "In parallel batch processing, the search are carried out on multiple threads simultaneously. This reduces the overall time required to test your algorithm on all the given scenarios. One drawback is that it is not very easy to debug your code with parallel batch processing."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "import os\n",
    "import sys\n",
    "\n",
    "# add the folder containing batch processing script into python path\n",
    "sys.path.append(os.path.join(os.getcwd(), \"../../\"))\n",
    "\n",
    "from SMP.batch_processing.batch_processing_parallel import run_parallel_processing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Config file loaded and logger created.\n",
      "18 scenarios skipped.\n",
      "ScenarioLoader Mode <DEFAULT>\n",
      "Run on all scenarios, except the skipped scenarios\n",
      "Number of scenarios: 500\n",
      "Automaton loaded for vehicle type: BMW_320i\n",
      "Motion planner: astar\n",
      "Number of parallel processes: 4\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t         1\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         0\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t         2\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         0\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t         3\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         0\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t         4\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         0\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario ARG_Carcarana-13_1_T-1        ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[119.77036 909.17741]\n",
      "Received position=[120.95186834 908.3848433 ]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t         5\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         0\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario ARG_Carcarana-2_3_T-1         ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ -42.345871 -160.47532 ]\n",
      "Received position=[ -40.9557694  -160.77820855]\n",
      "\n",
      "Something went wrong while processing scenario ARG_Carcarana-11_1_T-1        ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 4.8528764e-02 -3.2340290e+02]\n",
      "Received position=[   1.44568456 -323.67137644]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t         6\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         0\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t         7\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         0\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario ARG_Carcarana-5_2_T-1         ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 494.82773 -126.8882 ]\n",
      "Received position=[ 496.22706285 -127.14508814]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t         8\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         0\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario ARG_Carcarana-3_3_T-1         ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 350.5634  -581.96265]\n",
      "Received position=[ 351.95521582 -582.25756124]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t         9\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         0\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        10\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         1\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Aarschot-11_1_T-1         ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 978.34587 -134.32111]\n",
      "Received position=[ 978.1336582  -132.91430863]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        11\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         1\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario ARG_Carcarana-7_1_T-1         ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[369.30293 632.30164]\n",
      "Received position=[369.59696047 633.69364216]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        12\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         1\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Aarschot-3_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-257.22216 -211.03686]\n",
      "Received position=[-257.08557093 -212.45300524]\n",
      "\n",
      "Something went wrong while processing scenario BEL_Aarschot-1_2_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-624.03791 -272.56536]\n",
      "Received position=[-624.06895297 -271.14298162]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        13\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         1\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        14\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         1\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario ARG_Carcarana-9_2_T-1         ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-135.79707  392.48165]\n",
      "Received position=[-136.07449687  391.08624387]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        15\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         1\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Something went wrong while processing scenario BEL_Aarschot-5_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-340.83927  517.00733]\n",
      "Received position=[-340.99528805  515.59319341]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        16\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         1\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Beringen-8_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[1000.9426   873.36308]\n",
      "Received position=[1002.02312645  874.28859959]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        17\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         1\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        18\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         2\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Beringen-1_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-372.76765  718.10163]\n",
      "Received position=[-374.06335778  717.51403723]\n",
      "\n",
      "Something went wrong while processing scenario BEL_Nivelles-16_2_T-1         ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-500.27479 -487.31406]\n",
      "Received position=[-500.90810278 -488.58804542]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        19\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         2\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        20\n",
      "Something went wrong while processing scenario BEL_Nivelles-10_1_T-1         ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 254.87974 -988.86832]\n",
      "Received position=[ 256.29944913 -988.96078567]\n",
      "\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         2\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        21\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         2\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Nivelles-18_2_T-1         ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-406.68424 -173.69798]\n",
      "Received position=[-406.24169312 -172.34584236]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        22\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         2\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Nivelles-1_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[861.1144  550.74041]\n",
      "Received position=[862.11473224 551.75207167]\n",
      "\n",
      "Something went wrong while processing scenario BEL_Nivelles-19_1_T-1         ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-912.81802 -636.72001]\n",
      "Received position=[-913.99329303 -635.91822621]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        23\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         2\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        24\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         2\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Nivelles-20_1_T-1         ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-883.77781 -626.00842]\n",
      "Received position=[-883.05163844 -624.78498271]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        25\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         2\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Putte-10_2_T-1            ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[65.630609   1.1482173]\n",
      "Received position=[65.00450737  2.42576209]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        26\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         2\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Nivelles-4_2_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[712.78015 578.7309 ]\n",
      "Received position=[712.75595171 577.30838871]\n",
      "\n",
      "Something went wrong while processing scenario BEL_Putte-11_2_T-1            ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 313.42285 -473.63943]\n",
      "Received position=[ 314.80052628 -473.99458068]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        27\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         2\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        28\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         2\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Nivelles-3_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-923.52766 -629.01212]\n",
      "Received position=[-924.67999962 -628.17771163]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        29\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         2\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Nivelles-9_2_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 794.20686 -936.64096]\n",
      "Received position=[ 793.01079862 -937.41138917]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        30\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         3\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        31\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         3\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        32\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Putte-3_1_T-1             ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 745.09359 -611.39303]\n",
      "Received position=[ 745.22868723 -612.80931834]\n",
      "\n",
      "Something went wrong while processing scenario BEL_Putte-2_1_T-1             ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[640.08333 973.80808]\n",
      "Received position=[640.90180832 974.97178837]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        33\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        34\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Putte-6_1_T-1             ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 922.513   -456.17937]\n",
      "Received position=[ 923.77498321 -456.83627358]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Something went wrong while processing scenario BEL_Putte-4_2_T-1             ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-716.88753 -779.29154]\n",
      "Received position=[-718.29075537 -779.05684339]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        35\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        36\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Wervik-1_4_T-1            ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 83.586002 966.79291 ]\n",
      "Received position=[ 83.0087355  968.09325123]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        37\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Wervik-2_2_T-1            ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 474.8616  -307.86904]\n",
      "Received position=[ 475.55361594 -309.11211597]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        38\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Wervik-4_1_T-1            ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 399.004  -547.5064]\n",
      "Received position=[ 398.2492067  -546.30041036]\n",
      "\n",
      "Something went wrong while processing scenario BEL_Zaventem-4_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-303.0879  -188.79662]\n",
      "Received position=[-303.49898233 -187.4345865 ]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        39\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Zaventem-3_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-573.1947   585.25636]\n",
      "Received position=[-571.77771131  585.12881791]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        40\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Zaventem-1_2_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-406.93313 -114.97304]\n",
      "Received position=[-407.22894387 -113.58141574]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        41\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        42\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Zwevegem-3_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-712.00999 -458.4226 ]\n",
      "Received position=[-711.55935572 -459.77206385]\n",
      "\n",
      "Something went wrong while processing scenario BEL_Zaventem-5_3_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-726.49283  526.7991 ]\n",
      "Received position=[-727.45401715  527.84802478]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        43\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        44\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Zwevegem-2_3_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 911.87194 -343.99418]\n",
      "Received position=[ 912.96857998 -344.90054896]\n",
      "\n",
      "Something went wrong while processing scenario BEL_Zwevegem-5_2_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-27.763046 459.09773 ]\n",
      "Received position=[-28.19318681 460.45386525]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        45\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        46\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Something went wrong while processing scenario BEL_Zwevegem-7_2_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 639.17472 -217.32036]\n",
      "Received position=[ 637.97076647 -218.07839682]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        47\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario BEL_Zwevegem-8_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 43.346717 158.61832 ]\n",
      "Received position=[ 42.27647868 159.55571739]\n",
      "\n",
      "Something went wrong while processing scenario BEL_Zwevegem-8_4_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 40.97144 160.79867]\n",
      "Received position=[ 39.9605145 161.7997462]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        48\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        49\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario DEU_Backnang-4_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-260.53013   -94.975411]\n",
      "Received position=[-259.30821795  -94.24667588]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        50\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario DEU_Backnang-5_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[139.3091  134.32298]\n",
      "Received position=[139.82192792 132.99590372]\n",
      "\n",
      "Something went wrong while processing scenario DEU_Backnang-6_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[592.07521 184.39103]\n",
      "Received position=[590.95860718 185.27268871]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        51\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        52\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario DEU_Backnang-1_2_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-546.1219   286.09241]\n",
      "Received position=[-544.75367194  285.70244089]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        53\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario DEU_Backnang-9_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-126.38002 -198.21601]\n",
      "Received position=[-125.06482698 -197.67343167]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        54\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario DEU_BadEssen-4_1_T-1          ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-463.1657   205.09055]\n",
      "Received position=[-464.48722498  205.61751835]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        55\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario DEU_BadWaldsee-4_2_T-1        ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 394.62151 -680.29984]\n",
      "Received position=[ 393.80545159 -679.13443337]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        56\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario DEU_BadWaldsee-4_5_T-1        ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[ 394.15228 -679.64922]\n",
      "Received position=[ 393.31737075 -678.49724324]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        57\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Something went wrong while processing scenario DEU_BadEssen-3_1_T-1          ]Something went wrong while processing scenario DEU_BadWaldsee-1_1_T-1        ]\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-354.91696  575.70917]\n",
      "Received position=[-353.8353872  574.7848734]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-176.98395  112.56191]\n",
      "Received position=[-178.4063918   112.58989688]\n",
      "\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        58\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        59\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario DEU_Bilderstoeckchen-2_3_T-1  ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[381.50165 129.68371]\n",
      "Received position=[382.01112357 131.01207765]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        60\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario DEU_Bilderstoeckchen-4_1_T-1  ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 1\n",
      "Expected position=[-286.47729  218.25314]\n",
      "Received position=[-285.10300022  217.88510259]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        61\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "Something went wrong while processing scenario DEU_Flensburg-13_1_T-1        ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 123\n",
      "Expected position=[151.11456 165.34444]\n",
      "Received position=[152.4177271  165.91529851]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        62\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         0\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        63\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         1\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        64\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         2\n",
      "==================================================\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        65\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         3\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        66\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         4\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        67\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         5\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        68\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         6\n",
      "==================================================\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        69\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         7\n",
      "==================================================\n",
      "Something went wrong while processing scenario DEU_Flensburg-20_1_T-1        ]\n",
      "Traceback (most recent call last):\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 301, in process_scenario\n",
      "    is_valid_solution = save_solution(scenario=scenario, planning_problem_set=planning_problem_set,\n",
      "  File \"/commonroad/commonroad-search/tutorials/4_batch_processing/../../SMP/batch_processing/process_scenario.py\", line 200, in save_solution\n",
      "    if valid_solution(scenario, planning_problem_set, solution)[0]:\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 376, in valid_solution\n",
      "    starts_at_correct_state(solution, planning_problem_set),\n",
      "  File \"/opt/conda/lib/python3.9/site-packages/commonroad_dc/feasibility/solution_checker.py\", line 342, in starts_at_correct_state\n",
      "    raise SolutionCheckerException(msg)\n",
      "commonroad_dc.feasibility.solution_checker.SolutionCheckerException: Planning Problem Solution trajectory does not start at the initial_state of the planning problem with ID: 123\n",
      "Expected position=[ 45.699165 232.52175 ]\n",
      "Received position=[ 44.70079671 233.53534986]\n",
      "\n",
      "\n",
      "==================================================\n",
      "Scenario being processed:\t        70\n",
      "Solution found:               \t         0\n",
      "Solution found but invalid:   \t         0\n",
      "Solution not found:           \t         4\n",
      "Exception occurred:           \t         0\n",
      "Time out:                     \t         7\n",
      "==================================================\n"
     ]
    }
   ],
   "source": [
    "run_parallel_processing()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Sequential Batch Processing\n",
    "\n",
    "Alternatively, one can use the `SMP/batch_processing/batch_processing_sequential.py` script to carry out the search sequentially on a single thread. This is a more user-friendly approach if you wish you debug your code in IDES (e.g. creating breakpoints in PyCharm) but still have it run against multiple scenarios."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from SMP.batch_processing.batch_processing_sequential import run_sequential_processing\n",
    "run_sequential_processing()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  },
  "vscode": {
   "interpreter": {
    "hash": "2f6eab2d63de360a1b566290c617c31ba0315e2d992e7daa4351f45c5ea4c1ba"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
